
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-x-cluster-x-k8s-io-v1alpha1-machinemetadata
  failurePolicy: Fail
  name: mmachinemetadata.kb.io
  rules:
  - apiGroups:
    - x-cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinemetadata
